### ISSUE TITLE
Can not find fed Beverly Crusher

### ISSUE THREAD

**Issue by KFNEXUS** [KFNEXUS/KFNEXUS.github.io#19]
Can not find fed Beverly Crusher and she disappeared from all my saved lists. 
[https://s30.postimg.org/s4w1nas5t/bevbug.png](https://s30.postimg.org/s4w1nas5t/bevbug.png)

**Comment by jsterner73** [comment]
Some cards are missing after the last commit, where CrazyVulcan did some reorganizing in the file. I found Deanna Troi is missing as well. Since the order has been changed I cannot so which other cards are also missing. I would suggest going back to the version before the reorganizing and adding the last ship again without reorganizing the file.

@CrazyVulcan can you do that please?

**Comment by CrazyVulcan** [comment]
I will fix it immediately, sorry I am trying to get every upgrade sorted by faction and cost. And all the Captains sorted by Captain Skill

**Comment by CrazyVulcan** [comment]
OK while I still plan on arranging the Captains in order of their Captain Skill I have reset and re updated the data.json from my backup.
